- internal/fusefrontend/file.go
Many thanks to @rfjakob for assistance in tracking this down.
> Fix missing Owner coercion for already-open files (#117)

- internal/fusefrontend_reverse/reverse_longnames.go
> fusefrontend_reverse: Add a missing Close() call

- tests/example_filesystems/example_filesystems_test.go
To show that https://github.com/rfjakob/gocryptfs/issues/163 has been fixed.
I've added the tests to `example_filesystems` because we need a fixed master key here.
Before c547673529cb4934ab885081f5682e85aa994f79 the two tests failed.
> tests: Add test for access to encrypted version of '.' and '..'

- internal/fusefrontend/fs.go
- internal/nametransform/longnames.go
- tests/matrix/matrix_test.go
Fixes https://github.com/rfjakob/gocryptfs/issues/170
> fusefrontend: Fix longname handling for renames with existing target

- internal/fusefrontend_reverse/rfs.go
Also fixes another possible FD leak
> Use openBackingDir in Readlink and GetAttr

- internal/fusefrontend_reverse/rfile.go
**Note:** I am currently using `FromStat` to convert the syscall result to a `fuse.Attr` sruct and then `IsRegular()` to check if the handle refers to a regular file. If you prefer a different method (for example, manually checking the bits in the struct) please let me know.
Steps to reproduce:
* Create a regular reverse mount point
* Create a file "test" in the original directory
* Access the corresponding encrypted directory in the mount point (ls <encrypted dir>)
* Quickly delete the file in the original data - instead create a device node
* Access the file again, it will access the device node and attempt to read from it
Fixes https://github.com/rfjakob/gocryptfs/issues/187
> fusefrontend_reverse: Reject access to device nodes in newFile function

- Documentation/MANPAGE.md
From Debian packaging. Thank you!
> Fix spelling

- Documentation/MANPAGE-XRAY.md
From Debian packaging. Couldn't find a manpage for the xray tool. Thank you!
> Provide basic man page for xray tool

- README.md
Hello.
I am proposing a change to the text in your readme before the link to my cppcryptfs project.  
Please consider accepting it.
> update description of link to cppcryptfs project

- .gitignore
- Documentation/CLI_ABI.md
- Documentation/extractloop.md
- README.md
- fsck.go
- internal/contentenc/content.go
- internal/contentenc/intrablock.go
- internal/exitcodes/exitcodes.go
- internal/nametransform/dirivcache/dirivcache.go
- internal/nametransform/names.go
- internal/stupidgcm/stupidgcm_test.go
- tests/defaults/main_test.go
- tests/example_filesystems/example_filesystems_test.go
- tests/fuse-unmount.bash
- tests/reverse/correctness_test.go
Mostly detected with the 'codespell' utility, but also includes some
manual grammar fixes.
> Assorted spelling fixes.

- main.go
> main: Remove a duplicate word in a comment.

- internal/nametransform/longnames.go
Handle errors in the same way as in `WriteDirIV`.
Should we somehow unify those two functions?
> nametransform: Delete incomplete longname files on error.

- init_dir.go
- internal/fusefrontend/ctlsock_interface.go
- internal/fusefrontend/fs_dir.go
- internal/fusefrontend/openbackingdir.go
- internal/fusefrontend/openbackingdir_test.go
- internal/nametransform/longnames.go
- internal/syscallcompat/open_nofollow.go
- tests/test_helpers/helpers.go
Several fixes for the `symlink_race` branch.
> Symlink race fixes

- fsck.go
When running as a regular user, error EACCES does not necessarily mean that the
file/directory/xattr is corrupt, but just that we do not have sufficient access
permissions. Add a hint that running as root can be used to check everything.
Fixes: https://github.com/rfjakob/gocryptfs/issues/309
----
Note that I decided against using `chmod` since this is not necessarily sufficient to get access in a multi-user environment. Also, it is too risky to leave behind the file system in an inconsistent state when the user cancels `fsck`.
> fsck: Do not show files/directories without access permissions as corrupt.

- internal/fusefrontend/fs.go
Fixes https://github.com/rfjakob/gocryptfs/issues/328
-----
Feel free to just close this if you have already fixed it in your local branch.
> fusefrontend: Check result of Fchmod syscall.

- Documentation/MANPAGE.md
> Update manpage examples

- Documentation/MANPAGE.md
follow up from https://github.com/rfjakob/gocryptfs/issues/141
> MANPAGE: add a note on enabling Trash on macOS

- contrib/gocryptfssh
See https://github.com/rfjakob/gocryptfs/issues/750
> Added contrib/gocryptfssh

- Documentation/MANPAGE.md
> Removed repeated "conflicts" from MANPAGE.md

- internal/fusefrontend/file.go
> fusefrontend: fix excessive file fragmentation on BTRFS

- cli_args.go
- init_dir.go
- internal/configfile/config_file.go
- tests/cli/cli_test.go
> init_dir: use masterkey arg

- internal/fusefrontend/file.go
- internal/fusefrontend/file_allocate_truncate.go
- internal/fusefrontend/file_holes.go
`File` only gets created via `NewFile()` with the reference from the root node, but each file has a ref on the root node itself as well, thus its redundant.
[tests look good I guess](https://github.com/user-attachments/files/21165262/testoutput.txt)
[See here for related discussion](https://github.com/rfjakob/gocryptfs/discussions/933)
> remove redundant contentEnc reference from file struct

- .github/dependabot.yml
Checks weekly for updates of GitHub actions in the workflow directory.
Should update the old versions mentioned in https://github.com/rfjakob/gocryptfs/issues/940
> Dependabot workflow for action updates
