rfjakob/gocryptfs

internal/fusefrontend_reverse/rfs.go
The [Stat_t.Dev](https://golang.org/pkg/syscall/#Stat_t) docs say `unit64`, but on [macOS amd64](https://golang.org/src/syscall/ztypes_darwin_amd64.go) it's an `int32`.
Forcing a cast to make macOS happy (see #15).
=> fusefrontend_reverse cast Stat_t.Dev to uint64

Documentation/MANPAGE.md, cli_args.go
Just a small PR to further explain the use of 'scryptn' parameter by telling the possible values.
Actually, I was playing around with the parameters of gocryptfs, and I had to debug the code to understand that the command line parameter is expected to be the exponent instead of the final value.
The error I was getting was a bit confusing:
```
gocryptfs -init -scryptn 2048 ram_ciphertext/
Choose a password for protecting your files.
Password: 
Repeat: 
2017/03/25 14:30:58 DeriveKey failed: scrypt: N must be > 1 and a power of 2
panic: DeriveKey failed: scrypt: N must be > 1 and a power of 2
```
=> Further explain the use of 'scryptn' parameter

Documentation/MANPAGE.md, README.md, cli_args.go, internal/fusefrontend/args.go, internal/fusefrontend/fs.go, internal/fusefrontend_reverse/rfs.go, main.go, mount.go
This is a subset of what was previously proposed in #53. It permits a gocryptfs store backed by storage owned by user A (and, potentially, with filesystem-level mount options coercing ownership to user A) to be presented as readable and writable to user B, should user A invoke gocryptfs with `force_owner` passing user B's UID and GID.
=> Implement force_owner option to display ownership as a specific user.

Documentation/MANPAGE.md, cli_args.go, init_dir.go, internal/configfile/config_file.go, internal/configfile/config_test.go, tests/cli/cli_test.go
Allows to use /dev/random for generating the master key instead of the
default Go implementation. When the kernel random generator has been
properly initialized both are considered equally secure, however:
* Versions of Go prior to 1.9 just fall back to /dev/urandom if the
getrandom() syscall is blocking (Go Bug #19274)
* Kernel versions prior to 3.17 do not support getrandom(), and there
is no check if the random generator has been properly initialized
before reading from /dev/urandom
This is especially useful for embedded hardware with low-entroy. Please
note that generation of the master key might block indefinitely if the
kernel cannot harvest enough entropy.
=> main: Add '-devrandom' commandline option

internal/nametransform/names.go
=> nametransform: Return error if decrypted name is '.' or '..'

internal/fusefrontend/fs_dir.go
Fixes https://github.com/rfjakob/gocryptfs/issues/171
=> fusefrontend: Skip gocryptfs.diriv handling when directory was deleted successfully

internal/fusefrontend_reverse/reverse_longnames.go, tests/reverse/ctlsock_test.go
Fixes https://github.com/rfjakob/gocryptfs/issues/168
I decided to use the dir instead of the dirIV because it seems a bit easier here (especially when the dirIV could be variable length).
=> fusefrontend_reverse: Do not mix up cache information for different directories

internal/fusefrontend/fs.go, internal/fusefrontend/names.go, internal/syscallcompat/sys_darwin.go, internal/syscallcompat/sys_linux.go, tests/matrix/matrix_test.go
This set fixes:
* Some bugs in the recently introduced `Fchownat` syscall wrapper. Unfortunately I do not have any macOS machine available, so please verify that everything still works after these changes.
* Partially issue #177 (the symlink part)
* Issue #176
* Partially issue #174 (the mknod and unlink part)
In addition the set introduces a `openBackingPath` helper to do path conversion and open a handle to the directory. This could be especially useful later for fixing issue #165.
Please let me know what you think. Also feel free to cherry-pick certain patches if you want to solve certain issues in a different way.
=> Multiple fixes for PlaintextNames mode

init_dir.go, internal/fusefrontend/fs.go, internal/fusefrontend/fs_dir.go, internal/nametransform/diriv.go, internal/nametransform/longnames.go, internal/syscallcompat/sys_darwin.go, internal/syscallcompat/sys_linux.go, tests/test_helpers/helpers.go
Patch 1 fixes an existing TODO in the code.
Patch 2 and 3 changes the implementation of Chmod and Chown, such that `openBackingPath` and *at() syscalls are used. The general idea would be that in the long term, we try to use `openBackingPath` everywhere. When we later want to harden gocryptfs against symlink race-conditions (maybe optional, since it probably will be a bit slower), it is sufficient to change only a single function, instead of adding checks everywhere in the code.
Patch 4 should fix the remaining issue from #177.
=> Use *at() syscalls for Rmdir, Chmod, Chown and Mkdir

internal/fusefrontend/fs_dir.go, internal/nametransform/diriv.go, internal/syscallcompat/emulate.go, internal/syscallcompat/emulate_test.go
Patch 1 adds / updates the documentation as requested in https://github.com/rfjakob/gocryptfs/pull/179.
Patch 2 fixes the syscall emulation for absolute paths in a couple of functions. For absolute paths the `dirfd` should always be ignored. BTW, it would be nice if it would be possible to run the same emulation tests with emulation disabled, to test if the Linux syscalls actually work as expected.
Patch 3 updates two existing syscall wrappers with the new method (open current directory instead of caching the absolute path)
After this series only `emulateRenameat` remains a bit ugly. If you have any suggestions how to improve it without falling back to absolute paths ... ideas welcome ;)
=> Even more syscallcompat improvements

internal/fusefrontend_reverse/rfs.go
Also get rid of the defer - it is not really necessary here.
By the way: Do we also want to use the helper function here? It is not really suitable because we want only have a directory component.
=> fusefrontend_reverse: Use O_DIRECTORY in OpenDir implementation

internal/fusefrontend/fs.go, internal/syscallcompat/sys_common.go, tests/matrix/matrix_test.go
See https://github.com/rfjakob/gocryptfs/issues/174.
The second patch changes the code to use the use the more secure `Linkat` syscall.
=> Handle PlaintextNames mode in Link

internal/syscallcompat/unix2syscall_linux.go
Compiles with gccgo, but the test for emulated getdents fails. Related to issue #201.
=> Fix gccgo assignment error in Unix2syscall

internal/fusefrontend/xattr.go, internal/fusefrontend/xattr_linux.go, internal/fusefrontend/xattr_linux_unit_test.go, internal/fusefrontend/xattr_notlinux.go, internal/fusefrontend/xattr_unit_test.go
- Removed xattr filtering for non-Linux. "system." and "user." prefixes are only relevant for Linux.
- Small cleanup and additional tests.
Disallowing xattribute name like `com.apple` on Darwin results in creation of `._` files to store the respective attributes.
=> Improved xattr handling on non-linux systems

build.bash
This ensures that ./build.bash still works when the LDFLAGS environment
variable contains multiple options, e.g., LDFLAGS="-lpthread -lm". The
correct way of passing multiple options is discussed here:
https://github.com/golang/go/issues/6234
For some unknown reason, the method only works when -extldflags is the
last argument - is this a bug in Go?
------
Note that there are also other options to pass multiple options. The following syntax also seems to work:
```-extldflags \"$LDFLAGS\"```
It also seems to be possible to pass multiple `-extldflags` arguments:
```
-       GO_LDFLAGS="-extldflags=$LDFLAGS $GO_LDFLAGS"
+       for flag in $LDFLAGS; do
+               GO_LDFLAGS="$GO_LDFLAGS -extldflags=$flag"
+       done
```
=> build.bash: Escape LDFLAGS before passing them to 'go build'.

internal/fusefrontend/fs_dir.go
=> fusefrontend: Check the correct 'err' variable.

internal/fusefrontend/fs_dir.go
The directory was already created, so return success even if Fchownat fails.
The same error handling is already used if fs.args.PlaintextNames is false.
=> fusefrontend: Don't treat Fchownat error as failure in Mkdir.

internal/fusefrontend/file.go
The same condition is already checked a few lines above, and 'err' is not
changed inbetween.
=> fusefrontend: Remove unnecessary check in doRead function.

internal/configfile/config_file.go, internal/contentenc/content.go
Further raises the bar for recovering keys from memory.
The `scryptHash` array was already cleared in `EncryptKey` (added in 0efd220d1e10ac8e3d0048ff4d068cc8174e7185). However, the same logic is also required in `DecryptMasterKey`. In addition, there might be copies of the key stored in the cryptocore instance, so explicitly call `Wipe()` (using a returned callback method).
=> configfile: Explicitly wipe scrypt derived key after decrypting/encrypting master key.

internal/configfile/scrypt.go
Harmless, but should still be fixed to print a correct error message.
=> configfile: Fix a copy&paste error in validateParams method.

internal/fusefrontend/file.go
`blockData` contains the plaintext data, so there is nothing to subtract. Currently, the calculation can lead to underflows, e.g.,
```
ino12453470: Writing 18446744073709551585 bytes to block #8
```
=> fusefrontend: Fix debug message in doWrite() method.

internal/fusefrontend/file_allocate_truncate.go
When the old size is zero, there are no existing blocks to merge the
new data with. Directly use Ftruncate if the size is block-aligned.
Fixes https://github.com/rfjakob/gocryptfs/issues/305
=> fusefrontend: Allow to create sparse file of size 4096.

internal/fusefrontend_reverse/rfs.go
Go version go1.10.7 linux/amd64 complains with:
internal/fusefrontend_reverse/rfs.go:333: declaration of "entries" shadows
declaration at internal/fusefrontend_reverse/rfs.go:327
=> fusefrontend_reverse: Fix redeclaration of 'entries' variable.

internal/fusefrontend/xattr.go, internal/fusefrontend/xattr_darwin.go, internal/fusefrontend/xattr_linux.go, internal/syscallcompat/sys_common.go, tests/xattr/xattr_integration_test.go
Setting/removing extended attributes on directories was partially fixed with
commit eff35e60b63331e3e10f921792baa10b236a721d. However, on most file systems
it is also possible to do these operations without read access (see tests).
Since we cannot open a write-access fd to a directory, we have to use the
/proc/self/fd trick (already used for ListXAttr) for the other operations aswell.
For simplicity, let's separate the Linux and Darwin code again (basically revert
commit f320b76fd189a363a34bffe981aa67ab97df3362), and always use the
/proc/self/fd trick on Linux. On Darwin we use the best-effort approach with
openBackingFile() as a fallback.
More discussion about the available options is available in
https://github.com/rfjakob/gocryptfs/issues/308.
=> fusefrontend: Allow to set/remove xattr on directory without read permission.

internal/fusefrontend/fs.go, internal/fusefrontend/fs_dir.go, internal/syscallcompat/sys_darwin.go, internal/syscallcompat/sys_linux.go
Draft patch for the `Sereuid`/`Setregid` method on Linux. On Darwin, for now, just ignore the ownership problem at all. This will have to be adressed before `-allow_other` is usable again.
See https://github.com/rfjakob/gocryptfs/issues/339
=> Switch to Setreuid/Setregid method instead of manually changing ownership of files.

build.bash
Follow-up to #280 😉 
FYI, since `1.7` I included `gocryptfs-xray` to the Arch Linux distribution 👍
=> Add missing -ldflags for gocryptfs-xray

Makefile
I noticed you had created a Makefile! Nice nice 🙂 👍 
I'm proposing to extend Makefile with the following change. This will be a declaration of what a full distribution of gocryptfs must look like (two binaries, man page and license), and which build commands to run in order to prepare all the necessary files for installation (binaries and man page).
For example packaging for Arch Linux (and I assume all other distributions) will become as simple as running "make build" followed by "make install".
=> Add install goal in Makefile

codelingo.yaml, tests/fsck/fsck_test.go
Add a CodeLingo Tenet to protect the code from future instances of missing Close(), fixed in [this PR #162](https://github.com/rfjakob/gocryptfs/pull/162). Use the Tenet to find and fix several remaining cases of the issue.
=> Add CodeLingo Tenet to fix missing close file

package-source.bash
The local user ID (1026 jakob) appears in the source tarballs gocryptfs_v1.7_src.tar.gz and gocryptfs_v1.7_src-deps.tar.gz as the owner of VERSION, Documentation, and vendor. This issue is already fixed for the binary releases by commit 07f57314afb260d6b14227b932d66345c55ffab3, and the solution here is the same: use "tar --owner=root --group=root".
=> Prevent local user ID from appearing in source tarballs

Documentation/MANPAGE.md
=> Fix a typo in gocryptfs manpage.

Documentation/MANPAGE.md
When generating `man` pages, `pandoc` marks indented code blocks with the
`roff` macro `.nf`. That avoids a warning from `man` related to the long
line about the master key.
=> Fix 'cannot adjust line' warning from man in gocryptfs manpage.

contrib/getdents-debug/getdents/getdents.go
22e3eec15302eac28c1a2ac3f9af29c2c9e82a3c build was broken with error message:
contrib/getdents-debug/getdents/getdents.go:69: Printf format %v reads arg 2, but call has 1 arg
This commit fixes it by adding the missing argument.
=> contrib/getdents-debug: fix function call missing argument from 22e3eec

README.md
Add installation instructions for [MacPorts](https://www.macports.org/).
See: https://github.com/macports/macports-ports/blob/master/fuse/gocryptfs/Portfile
=> MacOS: Add install instructions for macports

internal/fusefrontend_reverse/virtualconf.go
Hey! There's a bug when using gocryptfs on macOS in reverse mode, where we can't access `gocryptfs.conf` in the virtual filesystem (supposed to map to `.gocryptfs.reverse.conf` in the real filesystem). It returns "Permission denied" instead.
FUSE debug logs looks like this when attempting to `cat gocryptfs.conf` in the virtual filesystem:
```
14:44:14.095207 rx 3: GETATTR n2
14:44:14.095229 tx 3:     OK, {tA=1s {M0100000 SZ=0 L=0 0:0 0 0:8954996 A 0.000000 M 0.000000 C 0.000000}}
14:44:14.099943 rx 4: ACCESS n2 {u=501 g=20 r}
14:44:14.099990 tx 4:     13=permission denied
```
I managed to fix it by implementing `Getattr` on `VirtualConfNode`.
Cheers!
=> Fix reverse gocryptfs.conf access on macOS

internal/stupidgcm/common_test.go
Signed-off-by: Abirdcfly <fp544037857@gmail.com>
see https://go.dev/play/p/EKemzC-_Uk4 for example:
```go
package main
import (
"testing"
)
func TestLastIndex(t *testing.T) {
t.Fatalf("print this line")
t.Log("not print")
}
/* output:
=== RUN   TestLastIndex
prog.go:8: print this line
--- FAIL: TestLastIndex (0.00s)
FAIL
Program exited.
*/
```
=> fix minor unreachable code caused by t.Fatal

gocryptfs-xray/paths_ctlsock.go, gocryptfs-xray/xray_main.go
gocryptfs-xray writes error output to stdout instead of stderr, which complicates it's usage in scripts.
This patch redirects error output to stderr.
=> Print errors to stderr

build.bash
Enables older CPUs (2008-2013) to take advantage of certain hardware accelerators.
Closes #828
=> Build with v2 extensions

Documentation/MANPAGE.md, cli_args.go, gocryptfs-xray/xray_main.go, init_dir.go, internal/configfile/config_file.go, internal/fido2/fido2.go, main.go
Add an option to specify user verification options for `fido2-assert -t`
Options will be saved to config file
Provide same functionality to #705 with simpler implementation
Resolve #702
=> Add user FIDO assert option

Documentation/MANPAGE.md
Fix error in the examples for `-fido2-assert-option`
=> Fix documentation error

mount.go
Merge stock kernel options with user-provided ones before passing to go-fuse.
Before: `-ko volname=custom` would result in `-o volname=mountpoint,volname=custom` to macFUSE.
After: `-ko volname=custom` would produce `-o volname=custom` with no duplicates.
Fixes #854 and #557
=> cli: deduplicate kernel options

Documentation/MANPAGE.md
The `--reverse` section of the manual has a reference to an `INIT FLAGS` section, but no such section exists. Change the reference to refer to the `INIT OPTIONS` section, which does exist.
=> manpage: Fix reference to manual section

Documentation/MANPAGE.md
=> manpage: fix typo in -passfile example

contrib/findholes/holes/holes.go, internal/contentenc/bpool.go, internal/ctlsocksrv/ctlsock_serve.go, internal/exitcodes/exitcodes.go, internal/fusefrontend/xattr_unit_test.go, internal/fusefrontend_reverse/node_helpers.go, internal/readpassword/read.go, internal/siv_aead/correctness_test.go, internal/syscallcompat/sys_linux.go, test.bash, tests/reverse/exclude_test.go, tests/reverse/inomap_test.go, tests/reverse/one_file_system_test.go, tests/reverse/xattr_test.go, tests/test_helpers/mount_unmount.go, tests/xattr/xattr_integration_test.go
Add staticcheck to test.bash for continuous static analysis
Fix nil pointer dereference in timesToTimespec function
The previous fix for deprecated fuse.UtimeToTimespec caused a panic because unix.TimeToTimespec doesn't handle nil pointers. This fix properly handles nil pointers by using unix.UTIME_OMIT while still using the non-deprecated unix.TimeToTimespec function.
Undo SA6002 changes and add staticcheck ignore directive instead
=> Fix all staticcheck errors in gocryptfs codebase
